targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**
      json_serializable:
        generate_for:
          - lib/**
        options:
          # Options for json_serializable
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

