version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: todo_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - todo-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  todo_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_backend
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MAX_CONNECTIONS=${DB_MAX_CONNECTIONS}
      - DB_CONNECTION_TIMEOUT=${DB_CONNECTION_TIMEOUT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-app
    restart: unless-stopped

networks:
  todo-app:
    driver: bridge
