name: todo_backend
description: A Todo - dart shelf server.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  shelf: 1.4.2
  shelf_router: 1.1.4
  shelf_cors_headers: 0.1.5
  postgres: 3.5.6
  dotenv: 4.2.0
  get_it: 8.0.3
  injectable: 2.5.0
  json_annotation: 4.9.0
  freezed_annotation: 3.1.0
  freezed: 3.2.0
  todo_proto:
    path: ./todo_proto

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: any
  json_serializable: 6.10.0
