name: todo_backend
description: A Todo - dart shelf server.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  shelf: 1.4.2
  shelf_router: 1.1.4
  shelf_cors_headers: 0.1.5
  dotenv: 4.2.0
  get_it: 8.0.3
  injectable: 2.5.0
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4
  fpdart: 1.1.1
  drift: 2.26.1
  postgres: 3.5.6
  drift_postgres: 1.3.1
  todo_proto:
    path: ./todo_proto

dev_dependencies:
  lints: 6.0.0
  test: 1.26.3
  build_runner: 2.5.4
  freezed: 2.5.8
  json_serializable: 6.9.5
  drift_dev: 2.26.1
  injectable_generator: 2.7.0

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"